### ISSUE TITLE
Exemplar instructions cause unexpected outcome

### ISSUE THREAD

**Issue by sgeorgedata** [Data-Simply/pyretailscience#13]
**Describe the bug**
Running the exemplar on the main page gives the following:

"2024-02-15 22:05:47.012 | INFO     | pyretailscience.data.cli:generate:36 - Generating data...
2024-02-15 22:05:50.239 | ERROR    | pyretailscience.data.simulation:__init__:212 - while parsing a mapping
  in "<unicode string>", line 14, column 1:
      churn_probability: '0.10'
    ^ (line: 14)
unexpected key not in schema 'average_days_between_purchases'
  in "<unicode string>", line 15, column 1:
      # Average days between purchas ... 
    ^ (line: 15)

"

**To Reproduce**
Steps to reproduce the behaviour:
1. Followed the instructions to install via pip install pyretailscience (this pulled all required packages)
2.  wget https://raw.githubusercontent.com/Data-Simply/pyretailscience/main/data/default_data_config.yaml
3. pyretailscience --config_file=default_data_config.yaml --seed=123 transactions.parquet

**Expected behavior**
Expected data file to be generated using the default data set. 

**Screenshots**
N/A

**Additional context**

grep tells me that this is in the .yaml file - and is set to 30 for cusomters

Is this a package compatibility issue?  I wonder if self.config = yaml.load(f.read(), schema).data isn't pulling the correct data. 

Python 3.10.11 (main, Apr  4 2023, 22:10:32) [GCC 12.2.0] on linux

**Comment by mvanwyk** [comment]
Thanks @sgeorgedata for the heads up!

I feel a bit silly. The issue is that the docs reference the most recent version of the config file, but the package requires the correct tagged version.

You can run the code with this config file instead.

`wget https://raw.githubusercontent.com/Data-Simply/pyretailscience/0.1.1/data/default_data_config.yaml`

I'll update the docs, and I'm about to release a new package as well.

**Comment by mvanwyk** [comment]
Fixed!

**Comment by sgeorgedata** [comment]
Great :-) I'll have another play with it later then. Thanks - I wondered if my build was just messing up TBF :-)

**Comment by mvanwyk** [comment]
All the little things from the repo are still missing, eg running the code examples in the documentation to ensure they pass 😄
